title: 2020-07-30-Welcome-to-my-first-blog
author: Jason Wan
email: delaynomore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  it is my first site. Thanks GithUb give me more chances. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
